\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{eecslides}[11/06/2012, v0.1]

\LoadClass[professionalfonts,10pt]{beamer}

\RequirePackage[utf8]{inputenc} % encodage UTF-8
\RequirePackage[OT1]{fontenc} % encodage de la police de caracteres

\RequirePackage[absolute,overlay]{textpos}

\RequirePackage[charter]{mathdesign}
\RequirePackage{berasans}
\RequirePackage[scaled]{beramono}

\usetheme{Rimouski}
\usecolortheme{Rimouski}

\RequirePackage{pgfcb}